name: "CI/CD"
description: Any changes/issues for the build process
labels: ["chore"]
assignees:
  - nopeitsnothing
body:

  - type: markdown
    attributes:
      value: |
        Briefly describe the issue or change.
        Note: you can also open a [discussion](https://github.com/Anon-Planet/thgtoa/discussions/new/choose).

  - type: textarea
    id: description
    attributes:
      label: Short description
      description: Please describe what should be fixed/changed.
      placeholder: Makefile doesn't build [document.md]. Here's how it can be fixed.
    validations:
      required: true
