blank_issues_enabled: false
contact_links:
  - name: Ask a Question about Anonymity, Privacy, or Security.
    url: https://github.com/Anon-Planet/thgtoa/discussions/new?category=general
    about: Feel free to ask us anything and we'll respond promptly

