name: "Donation"
description: Donation transparency report
labels: ["donation"]
body:

  - type: input
    attributes:
      label: Donation
      description: An [anonymous] donation was made [by whom]
      placeholder: "0.1 XXX was donated [from whom]"
    validations:
      required: true
