on:
  push:
    paths:
      - 'doc/**'

name: '✏️ Create PDF'

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mkrakowitzer/actions-makepdfs@master
      if: github.ref == 'refs/heads/main'
      with:
        markdown_dir: .
        output_dir: export
    - uses: actions/upload-artifact@v1
      with:
        name: platform-architecture-docs
        path: export