name: 🚀 Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish the Hitchhiker's Guide
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: anonymousplanet.net
